### ISSUE TITLE
Turbulent water bucket is replaced without checking one is already there

### ISSUE THREAD

**Issue by catwhisperer77** [ExeVirus/waterfalls#1] opened 2019-07-11 08:39 UTC
Steps to reproduce:

1. Add a bucket of water and quartz crystal in the whirlpool machine, and trigger the machine.
2. Wait for it to finish and produce a turbulent water bucket.
3. Without removing the first bucket from the output slot, add another bucket of water and quartz crystal, and trigger the machine.
4. The machine should process it and simply overwrite the turbulent water bucket.

Is this intended?

In keeping with furnace-type functionality, the whirlpool machine should probably check that the output is empty before starting processing. Alternatively, perhaps remove the output slot and swap the bucket of water in the input slot with a turbulent bucket.

**Comment by ExeVirus** [comment] 2019-07-11 12:35
That is not intended behavior, thank you for the catch, I just committed the code change, and will not allow a user to run the machine while a turbulent bucket is in the output slot.

I will have to rework the turbulent water machine in the future to act more like a furnace, but I have a lot on my plate, so it'll be a few weeks most likely.

**Closed as completed by ExeVirus** 2019-07-11 12:35 UTC
